# Generated by Django 5.1.7 on 2025-05-05 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating'), ('text', 'Text')], default='text', max_length=10)),
                ('max_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'form_questions',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('peer', 'Peer'), ('review', 'Review'), ('feedback', 'Feedback')], default='peer', max_length=10)),
                ('period', models.CharField(default='monthly', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_type', models.CharField(choices=[('numeric', 'Numeric'), ('text', 'Text')], default='text', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.formquestions')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_given', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.forms')),
            ],
            options={
                'db_table': 'form_responses',
            },
        ),
        migrations.AddField(
            model_name='formquestions',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.forms'),
        ),
    ]
