# Generated by Django 5.1.7 on 2025-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
            options={
                'db_table': 'form_questions',
            },
        ),
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'form_responses',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('self', 'Self'), ('peer', 'Peer')], default='self', max_length=10)),
                ('period', models.CharField(default='monthly', max_length=20)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
    ]
