# Generated by Django 5.1.7 on 2025-03-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('self', 'Self'), ('peer', 'Peer')], max_length=10)),
                ('period', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='FormResponses',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_received', to='users.users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_given', to='users.users')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.forms')),
            ],
            options={
                'db_table': 'form_responses',
            },
        ),
        migrations.CreateModel(
            name='FormQuestions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.forms')),
            ],
            options={
                'db_table': 'form_questions',
            },
        ),
    ]
