# Generated by Django 5.1.7 on 2025-03-16 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponses',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formresponses',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.forms'),
        ),
        migrations.AddField(
            model_name='formquestions',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.forms'),
        ),
    ]
