# Generated by Django 5.1.7 on 2025-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestions',
            options={'verbose_name': 'Form Question', 'verbose_name_plural': 'Form Questions'},
        ),
        migrations.AlterModelOptions(
            name='formresponses',
            options={'verbose_name': 'Form Response', 'verbose_name_plural': 'Form Responses'},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'verbose_name': 'Form', 'verbose_name_plural': 'Forms'},
        ),
    ]
