# Generated by Django 5.1.7 on 2025-04-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='goal_achieved_percentage',
        ),
        migrations.RemoveField(
            model_name='users',
            name='goal_deadline',
        ),
        migrations.RemoveField(
            model_name='users',
            name='goal_description',
        ),
        migrations.RemoveField(
            model_name='users',
            name='goal_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='goal_priority',
        ),
        migrations.RemoveField(
            model_name='users',
            name='goal_status',
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Achieved', 'Achieved'), ('Missed', 'Missed')], default='Pending', max_length=10)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('achieved_percentage', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
    ]
