# Generated by Django 5.1.7 on 2025-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aichatmessage',
            options={'ordering': ('timestamp',), 'verbose_name': 'AI Chat Message', 'verbose_name_plural': 'AI Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='userfaceimage',
            options={'verbose_name': 'User Face Image', 'verbose_name_plural': 'User Face Images'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
