# Generated by Django 5.1.7 on 2025-04-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_goal_achieved_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkincheckout',
            name='checkin_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='checkincheckout',
            name='checkout_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
