# Generated by Django 5.1.7 on 2025-05-06 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='face_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_face_images',
            },
        ),
        migrations.AddField(
            model_name='checkincheckout',
            name='is_valid_checkin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='checkincheckout',
            name='is_valid_checkout',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='checkincheckout',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_checkin_checkout_per_day'),
        ),
        migrations.AddField(
            model_name='userfaceimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
