# Generated by Django 5.1.7 on 2025-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_goals_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkincheckout',
            options={'verbose_name': 'Check-in/Check-out', 'verbose_name_plural': 'Check-in/Check-out'},
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='checkin_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='checkout_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='is_valid_checkin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkincheckout',
            name='is_valid_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
