# Generated by Django 5.1.7 on 2025-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deadline Extension Request',
                'verbose_name_plural': 'Deadline Extension Requests',
                'db_table': 'deadline_extension_requests',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Thực hiện chính', 'Thực hiện chính'), ('Đồng thực hiện', 'Đồng thực hiện'), ('Review', 'Review'), ('Test', 'Test'), ('Khác', 'Khác')], default='Thực hiện chính', max_length=50)),
                ('estimated_time', models.FloatField(blank=True, null=True)),
                ('actual_time', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('To-do', 'To-do'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Late', 'Late')], default='To-do', max_length=20)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
                'db_table': 'task_assignments',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('To-do', 'To-do'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Late', 'Late')], default='To-do', max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('estimated_time', models.FloatField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('total_time', models.FloatField(default=0.0)),
                ('is_tracking', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TeamProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(default='Member', max_length=50)),
            ],
            options={
                'verbose_name': 'Team Project Membership',
                'verbose_name_plural': 'Team Project Memberships',
                'db_table': 'team_project_memberships',
            },
        ),
        migrations.CreateModel(
            name='TimeEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'db_table': 'time_entries',
            },
        ),
    ]
