# Generated by Django 5.1.7 on 2025-05-21 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projects'),
        ),
        migrations.AddField(
            model_name='taskassignments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='projects.tasks'),
        ),
        migrations.AddField(
            model_name='deadlineextensionrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_requests', to='projects.tasks'),
        ),
        migrations.AddField(
            model_name='teamprojectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects'),
        ),
        migrations.AddField(
            model_name='teamprojectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_members',
            field=models.ManyToManyField(related_name='projects', through='projects.TeamProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timeentries',
            name='task_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.taskassignments'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['deadline'], name='tasks_deadlin_7f16a6_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['status'], name='tasks_status_031d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['start_date'], name='tasks_start_d_efea8c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignments',
            index=models.Index(fields=['task', 'user'], name='task_assign_task_id_7a04e8_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignments',
            index=models.Index(fields=['status'], name='task_assign_status_78cc4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignments',
            unique_together={('task', 'user', 'role')},
        ),
        migrations.AddIndex(
            model_name='deadlineextensionrequest',
            index=models.Index(fields=['task', 'status'], name='deadline_ex_task_id_6a7976_idx'),
        ),
        migrations.AddIndex(
            model_name='deadlineextensionrequest',
            index=models.Index(fields=['requested_by', 'status'], name='deadline_ex_request_7ab93a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamprojectmembership',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='timeentries',
            index=models.Index(fields=['task_assignment', 'start_time'], name='time_entrie_task_as_236df1_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentries',
            index=models.Index(fields=['start_time'], name='time_entrie_start_t_1b98e4_idx'),
        ),
    ]
