# Generated by Django 5.1.7 on 2025-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deadlineextensionrequest',
            options={'verbose_name': 'Deadline Request', 'verbose_name_plural': 'Deadline Requests'},
        ),
    ]
