# Generated by Django 5.1.7 on 2025-04-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_tasks_notes_alter_tasks_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20),
        ),
    ]
