# Generated by Django 5.1.7 on 2025-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_tasks_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignments',
            name='estimated_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tasks',
            index=models.Index(fields=['start_date'], name='tasks_start_d_efea8c_idx'),
        ),
    ]
