# Generated by Django 5.1.7 on 2025-04-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_taskassignments_estimated_time_tasks_completed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignments',
            name='status',
            field=models.CharField(choices=[('To-do', 'To-do'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Late', 'Late')], default='To-do', max_length=20),
        ),
    ]
