# Generated by Django 5.1.7 on 2025-03-14 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='teams',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(through='companies.TeamMembers', to='users.users'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.teams'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembers',
            unique_together={('team', 'user')},
        ),
    ]
