# Generated by Django 5.1.7 on 2025-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeKPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('achieved_percentage', models.FloatField(default=0.0, help_text='Percentage of target achieved')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('time_period', models.CharField(choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('evaluation', models.CharField(blank=True, choices=[('Exceeded', 'Exceeded'), ('Achieved', 'Achieved'), ('Partially Achieved', 'Partially Achieved'), ('Not Achieved', 'Not Achieved')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'employee_kpis',
            },
        ),
        migrations.CreateModel(
            name='KPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('kpi_type', models.CharField(choices=[('Quantitative', 'Quantitative'), ('Qualitative', 'Qualitative'), ('Efficiency', 'Efficiency'), ('Quality', 'Quality')], default='Quantitative', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(default=1.0, help_text='Weight for overall performance calculation')),
            ],
            options={
                'db_table': 'kpis',
            },
        ),
    ]
