# Generated by Django 5.1.7 on 2025-05-21 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kpis', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekpis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpis',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to a specific project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='projects.projects'),
        ),
        migrations.AddField(
            model_name='employeekpis',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_kpis', to='kpis.kpis'),
        ),
        migrations.AddIndex(
            model_name='employeekpis',
            index=models.Index(fields=['user', 'start_date'], name='employee_kp_user_id_2ebafc_idx'),
        ),
        migrations.AddIndex(
            model_name='employeekpis',
            index=models.Index(fields=['kpi', 'time_period'], name='employee_kp_kpi_id_889c8e_idx'),
        ),
    ]
