# Generated by Django 5.1.7 on 2025-05-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeekpis',
            options={'verbose_name': 'Employee KPI', 'verbose_name_plural': 'Employee KPIs'},
        ),
        migrations.AlterModelOptions(
            name='kpis',
            options={'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
    ]
