# Generated by Django 5.1.7 on 2025-05-04 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0003_kpis_employeekpis_changes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='EmployeeKPIs',
            name='task',
        ),
    ]
