# Generated by Django 5.1.7 on 2025-05-05 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpis', '0004_rename_employee_kpis_user_start_date_idx_employee_kp_user_id_2ebafc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeekpis',
            new_name='employee_kp_user_id_2ebafc_idx',
            old_name='employee_kpis_user_start_date_idx',
        ),
        migrations.RenameIndex(
            model_name='employeekpis',
            new_name='employee_kp_kpi_id_889c8e_idx',
            old_name='employee_kpis_kpi_period_idx',
        ),
        migrations.RemoveField(
            model_name='employeekpis',
            name='unit',
        ),
        migrations.AlterField(
            model_name='employeekpis',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeekpis',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_kpis', to='kpis.kpis'),
        ),
        migrations.AlterField(
            model_name='employeekpis',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeekpis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to=settings.AUTH_USER_MODEL),
        ),
    ]
